export const QUESTIONS_RECEIVING = 'QUESTIONS_RECEIVING';
export const QUESTIONS_RECEIVED = 'QUESTIONS_RECEIVED';
export const QUESTIONS_NOT_RECEIVED = 'QUESTIONS_NOT_RECEIVED';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const UPDATE_CORRECT_ANSWERS = 'UPDATE_CORRECT_ANSWERS';